import Head from 'next/head'
import { Row, Col, Input, Carousel } from "antd"
import { SearchOutlined, ShoppingCartOutlined } from '@ant-design/icons';
import { useState } from 'react';
import { img } from '../utils/helper';
import { reduceEachLeadingCommentRange } from 'typescript';

export default function Home() {
  interface IBrand {
    name: string;
    img: string;
  }

  interface ICategory {
    name: string;
    img: string;
    link: string;
  }

  interface IRecommendation {
    name: string;
    img: string;
    link: string;
    price: number;
  }

  const [brands] = useState<IBrand[]>([
    { name: "AAA", img: 'dodo.png' },
    { name: "Seventeen", img: 'dodo.png' },
    { name: "Booba", img: 'dodo.png' },
    { name: "Minutes", img: 'dodo.png' },
    { name: "Air Drop", img: 'dodo.png' },
    { name: "Fallen Down", img: 'dodo.png' },
    { name: "Water Up", img: 'dodo.png' },
  ])

  const [categories] = useState<ICategory[]>([
    { name: 'Shirt', img: '', link: '#' },
    { name: 'Polo', img: '', link: '#' },
    { name: 'T Shirt', img: '', link: '#' },
    { name: 'Short Pants', img: '', link: '#' },
    { name: 'Long Pants', img: '', link: '#' },
    { name: 'Accessories', img: '', link: '#' },
  ]);

  const [recomendations] = useState<IRecommendation[]>([
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
    { name: 'Shirt Now Exotic', price: 200, link: '#', img: 'dodo.png' },
  ]);

  return (
    <>
      <Head>
        <title>Rozi Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id='home'>
        <div className='flex justify-end'>
          <ul className='flex gap-5'>
            <li>
              <ShoppingCartOutlined style={{ fontSize: 30, color: 'white', marginTop: '5px' }} />
            </li>
            <li>
              <button className='bg-blue-600 text-white px-6 py-2 rounded-full'>LOGIN</button>
            </li>
          </ul>
        </div>
        <div className='h-5/6 grid justify-items-center content-center'>
          <Input.Search
            size='large'
            className='max-w-lg'
            placeholder="Search"
            allowClear
            enterButton={<SearchOutlined />}
          />
        </div>
      </section>

      <section>
        <div className="grid grid-cols-6 gap-5">
          {categories.map((cat, catKey) => (
            <div className='home-category' key={catKey}>
              {cat.name}
            </div>
          ))}
        </div>
      </section>

      <section className='px-32'>
        <div className="grid grid-cols-5 gap-5">
          {recomendations.map((rec, recKey) => (
            <div className='home-product' key={recKey}>
              <div className='home-product-content'>

              </div>
              <div className='home-product-detail'>
                <div className='flex justify-between'>
                  Price: ${rec.price}
                  <button>Detail</button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section>
        <Carousel slidesToShow={5}>
          {brands.map((brand, brandKey) => (

            <div className='brand' style={{ background: img(brand.img) }}></div>
          ))}
        </Carousel>
      </section>

      <footer className='home-footer grid grid-cols-2'>
        <div className='flex gap-5'>
          <div className='logo'></div>

          <div className='grid grid-cols-3 gap-3'>
            <div className="category">Shirt</div>
            <div className="category">Polo</div>
            <div className="category">T Shirt</div>
            <div className="category">Short Pants</div>
            <div className="category">Long Pants</div>
            <div className="category">Accessories</div>
          </div>
        </div>

        <div>
          <div>
            <p>Follow us</p>
            <div className='flex gap-5'>
              <div className='sosmed'>Instagram</div>
              <div className='sosmed'>TikTok</div>
            </div>
          </div>
          <div>
            <p>Address:</p>
            <p>Jl. Daniel Bohang, Ternate, North Moluccas, Indonesia</p>
            <p>admin@rozistore.com</p>
            <p>+62123456789</p>
          </div>
        </div>
      </footer>
    </>
  )
}
